### ISSUE TITLE
Multi-UAV

### ISSUE THREAD

**Issue by yonggaogit** [Zhefan-Xu/uav_simulator#1]
Nice Work! Thank you very much. But I have a question, How to add multi uav in simulator?

**Comment by Zhefan-Xu** [comment]
The current version does not support multi uav simulation, but it is not difficult to make adjustment for multi uav. I suggest to check the start.launch file and you might want to include mutiple spawn nodes. The only thing you will need to change is to add namespace to each uav topics.

**Comment by yonggaogit** [comment]
> The current version does not support multi uav simulation, but it is not difficult to make adjustment for multi uav. I suggest to check the start.launch file and you might want to include mutiple spawn nodes. The only thing you will need to change is to add namespace to each uav topics.

Thank you, I succeeded in following your advice
